# Generated by Django 3.0.2 on 2020-02-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.FilePathField(path='/img')),
                ('bestCase', models.TextField()),
                ('worstCase', models.TextField()),
                ('purpose', models.CharField(max_length=50)),
                ('categories', models.ManyToManyField(related_name='algorithms', to='algorithms.Category')),
            ],
        ),
    ]
