# Generated by Django 3.0.2 on 2020-02-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='image',
            field=models.FilePathField(path='algorithms/img'),
        ),
    ]
